//! The schema, written as **pure functions returning statements**.
//!
//! Keeping it apart from the migration runner is deliberate: it makes all generated DDL
//! **snapshot-testable without a running PostgreSQL**. For a "no magic strings" promise,
//! seeing the final SQL string in a test matters more than being able to execute it.

use dnqatv_core::model::{GlyphKind, Letter, Pos};
use sea_orm_migration::prelude::extension::postgres::{PgBinOper, Type, TypeCreateStatement};
use sea_orm_migration::prelude::*;

use crate::idens::{
    Entry, FrontMatter, Glyph, IdxMethod, IdxName, OpClass, Page, PgEnum, PgFn, PgType, SubEntry,
    ts_config_literal,
};

// ── Enum types, generated from the domain layer ──────────────────────────────

/// `CREATE TYPE entry_pos AS ENUM (…)`, generated by iterating [`Pos::ALL`].
///
/// Adding a variant to `Pos` makes it appear here automatically — there is no second list to drift.
pub fn create_pos_enum() -> TypeCreateStatement {
    Type::create()
        .as_enum(PgEnum::EntryPos)
        .values(Pos::ALL.map(|p| p.db_value().into_iden()))
        .to_owned()
}

/// `CREATE TYPE book_letter AS ENUM (…)` — the 22 letters in the EXACT printed order.
///
/// Order matters: the print runs `… H Y K …`, i.e. Y sits where I would be. Declaring the
/// Latin range would be wrong, and since Postgres compares enums by declaration order it
/// would break ordering as well.
pub fn create_letter_enum() -> TypeCreateStatement {
    Type::create()
        .as_enum(PgEnum::BookLetter)
        .values(Letter::ALL.map(|l| l.db_value().into_iden()))
        .to_owned()
}

pub fn create_glyph_kind_enum() -> TypeCreateStatement {
    Type::create()
        .as_enum(PgEnum::GlyphKind)
        .values(GlyphKind::ALL.map(|k| k.db_value().into_iden()))
        .to_owned()
}

// ── Tables ───────────────────────────────────────────────────────────────────

pub fn create_page_table() -> TableCreateStatement {
    Table::create()
        .table(Page::Table)
        .if_not_exists()
        .col(ColumnDef::new(Page::Id).integer().primary_key())
        .col(ColumnDef::new(Page::PdfPage).small_integer().not_null())
        // NULL on the three pages with no printed number — the two systems do not line up.
        .col(ColumnDef::new(Page::PrintedPage).small_integer())
        .col(ColumnDef::new(Page::Letter).custom(PgEnum::BookLetter))
        .col(ColumnDef::new(Page::ImagePath).text())
        .col(ColumnDef::new(Page::HeadFirst).text())
        .col(ColumnDef::new(Page::HeadLast).text())
        .to_owned()
}

pub fn create_glyph_table() -> TableCreateStatement {
    Table::create()
        .table(Glyph::Table)
        .if_not_exists()
        .col(ColumnDef::new(Glyph::Id).integer().primary_key())
        .col(ColumnDef::new(Glyph::Char).text().not_null().unique_key())
        .col(ColumnDef::new(Glyph::Codepoint).integer().not_null())
        .col(
            ColumnDef::new(Glyph::Kind)
                .custom(PgEnum::GlyphKind)
                .not_null(),
        )
        .col(ColumnDef::new(Glyph::ImagePath).text())
        .col(
            ColumnDef::new(Glyph::InIndex)
                .boolean()
                .not_null()
                .default(false),
        )
        .to_owned()
}

pub fn create_entry_table() -> TableCreateStatement {
    Table::create()
        .table(Entry::Table)
        .if_not_exists()
        .col(ColumnDef::new(Entry::Id).integer().primary_key())
        // NULL where the print uses an image for the glyph — 29 entries are like this.
        .col(ColumnDef::new(Entry::GlyphId).integer())
        .col(ColumnDef::new(Entry::PageId).integer().not_null())
        .col(ColumnDef::new(Entry::Seq).integer().not_null())
        .col(ColumnDef::new(Entry::Slug).text().not_null().unique_key())
        .col(ColumnDef::new(Entry::Reading).text().not_null())
        .col(ColumnDef::new(Entry::ReadingNorm).text().not_null())
        .col(ColumnDef::new(Entry::Alternate).text())
        // An array: 548 entries carry two labels.
        .col(
            ColumnDef::new(Entry::Pos)
                .array(ColumnType::custom(PgEnum::EntryPos))
                .not_null(),
        )
        .col(ColumnDef::new(Entry::Gloss).text().not_null().default(""))
        .col(ColumnDef::new(Entry::SubText).text().not_null().default(""))
        .col(
            ColumnDef::new(Entry::InheritsGlyph)
                .boolean()
                .not_null()
                .default(false),
        )
        .col(
            ColumnDef::new(Entry::NeedsReview)
                .boolean()
                .not_null()
                .default(false),
        )
        .col(
            ColumnDef::new(Entry::SearchDoc)
                .custom(PgType::TsVector)
                .generated(search_doc_expr(), true),
        )
        .foreign_key(
            ForeignKey::create()
                .from(Entry::Table, Entry::GlyphId)
                .to(Glyph::Table, Glyph::Id)
                .on_delete(ForeignKeyAction::Restrict),
        )
        .foreign_key(
            ForeignKey::create()
                .from(Entry::Table, Entry::PageId)
                .to(Page::Table, Page::Id)
                .on_delete(ForeignKeyAction::Restrict),
        )
        .to_owned()
}

pub fn create_sub_entry_table() -> TableCreateStatement {
    Table::create()
        .table(SubEntry::Table)
        .if_not_exists()
        .col(ColumnDef::new(SubEntry::Id).integer().primary_key())
        .col(ColumnDef::new(SubEntry::EntryId).integer().not_null())
        .col(ColumnDef::new(SubEntry::Seq).integer().not_null())
        .col(ColumnDef::new(SubEntry::HanForm).text())
        .col(ColumnDef::new(SubEntry::HanExpanded).text())
        .col(ColumnDef::new(SubEntry::Form).text().not_null())
        .col(ColumnDef::new(SubEntry::FormExpanded).text().not_null())
        .col(
            ColumnDef::new(SubEntry::Definition)
                .text()
                .not_null()
                .default(""),
        )
        .col(
            ColumnDef::new(SubEntry::NeedsReview)
                .boolean()
                .not_null()
                .default(false),
        )
        .foreign_key(
            ForeignKey::create()
                .from(SubEntry::Table, SubEntry::EntryId)
                .to(Entry::Table, Entry::Id)
                .on_delete(ForeignKeyAction::Cascade),
        )
        .to_owned()
}

pub fn create_front_matter_table() -> TableCreateStatement {
    Table::create()
        .table(FrontMatter::Table)
        .if_not_exists()
        .col(ColumnDef::new(FrontMatter::Id).integer().primary_key())
        .col(
            ColumnDef::new(FrontMatter::Slug)
                .text()
                .not_null()
                .unique_key(),
        )
        .col(ColumnDef::new(FrontMatter::Title).text().not_null())
        .col(ColumnDef::new(FrontMatter::Body).text().not_null())
        .col(
            ColumnDef::new(FrontMatter::PdfPage)
                .small_integer()
                .not_null(),
        )
        .to_owned()
}

// ── Generated column expressions ─────────────────────────────────────────────

/// `to_tsvector('vi_simple'::regconfig, coalesce(<column>, ''))`
///
/// **Why not `PgFunc::to_tsvector`:** that function takes `regconfig` as a **`u32` OID**,
/// and the OID of `vi_simple` only exists once the configuration has been created — it
/// cannot be known while writing the migration. This uses the cast `'vi_simple'::regconfig`
/// instead, still fully typed via [`Func::cast_as`], letting Postgres resolve the OID at parse time.
fn to_tsvector(column: Entry) -> Expr {
    Func::cust(PgFn::ToTsvector)
        .arg(Func::cast_as(ts_config_literal(), PgType::RegConfig))
        .arg(Func::cust(PgFn::Coalesce).arg(Expr::col(column)).arg(""))
        .into()
}

/// `setweight(<expression>, '<rank>')`
fn setweight(expr: Expr, weight: &str) -> Expr {
    Func::cust(PgFn::Setweight).arg(expr).arg(weight).into()
}

/// The `search_doc` column, concatenated with weights.
///
/// The three weight ranks match the three ways users search:
/// **A** the reading (forward lookup) · **B** the main definition · **C** sub-entry text (reverse lookup).
///
/// `sub_text` has to be a column of the `entry` table itself: a Postgres generated column
/// cannot reference another table, so `sub_entry` cannot be folded in directly.
fn search_doc_expr() -> Expr {
    setweight(to_tsvector(Entry::Reading), "A")
        .binary(
            PgBinOper::Concatenate,
            setweight(to_tsvector(Entry::Gloss), "B"),
        )
        .binary(
            PgBinOper::Concatenate,
            setweight(to_tsvector(Entry::SubText), "C"),
        )
}

// ── Indexes ────────────────────────────────────────────────────────────────────

/// GIN on `search_doc` — the full-text search index.
pub fn create_search_doc_index() -> IndexCreateStatement {
    Index::create()
        .name(IdxName::EntrySearchDoc.into_iden().to_string())
        .table(Entry::Table)
        .col(Entry::SearchDoc)
        .index_type(IndexType::Custom(IdxMethod::Gin.into_iden()))
        .to_owned()
}

/// GIN + `gin_trgm_ops` on `reading_norm` — for unaccented search and typo suggestions.
pub fn create_reading_norm_trgm_index() -> IndexCreateStatement {
    Index::create()
        .name(IdxName::EntryReadingNormTrgm.into_iden().to_string())
        .table(Entry::Table)
        .col(IndexColumn::from(Entry::ReadingNorm).with_operator_class(OpClass::GinTrgm))
        .index_type(IndexType::Custom(IdxMethod::Gin.into_iden()))
        .to_owned()
}

/// B-tree on `reading` — exact and prefix lookup.
pub fn create_reading_index() -> IndexCreateStatement {
    Index::create()
        .name(IdxName::EntryReading.into_iden().to_string())
        .table(Entry::Table)
        .col(Entry::Reading)
        .to_owned()
}

pub fn create_sub_entry_index() -> IndexCreateStatement {
    Index::create()
        .name(IdxName::SubEntryEntryId.into_iden().to_string())
        .table(SubEntry::Table)
        .col(SubEntry::EntryId)
        .to_owned()
}

// ── Drop lists ───────────────────────────────────────────────────────────────

/// Tables in drop order — the reverse of the foreign-key dependency chain.
pub fn all_tables_in_drop_order() -> Vec<DynIden> {
    vec![
        SubEntry::Table.into_iden(),
        Entry::Table.into_iden(),
        FrontMatter::Table.into_iden(),
        Glyph::Table.into_iden(),
        Page::Table.into_iden(),
    ]
}

/// Every enum type in the schema.
pub fn all_types() -> Vec<DynIden> {
    vec![
        PgEnum::EntryPos.into_iden(),
        PgEnum::BookLetter.into_iden(),
        PgEnum::GlyphKind.into_iden(),
    ]
}

/// Add `entry.shape_note` — how the shape of an unencodable glyph was described.
///
/// A separate statement rather than a column on [`create_entry_table`], because the schema
/// migration has already run on live databases: editing an applied migration would leave
/// them without the column while the code expected it.
///
/// Nullable on purpose, and it stays `NULL` for every entry that has a glyph. It is filled
/// only for the 29 entries where the 2026 edition sets an image, and only from a dossier row
/// a person has signed — see the import step. Nothing describes a shape on its own authority.
pub fn add_entry_shape_note() -> TableAlterStatement {
    Table::alter()
        .table(Entry::Table)
        .add_column_if_not_exists(ColumnDef::new(Entry::ShapeNote).text())
        .to_owned()
}

/// Undo [`add_entry_shape_note`].
pub fn drop_entry_shape_note() -> TableAlterStatement {
    Table::alter()
        .table(Entry::Table)
        .drop_column(Entry::ShapeNote)
        .to_owned()
}
